site_name: Timothy's portfolio
site_url: https://portfolio.bailitaotao.com

theme:
  name: material
  logo: assets/images/logo-tao-no-frame.svg
  favicon: assets/images/logo-tao-no-frame.svg
  palette:
    primary: white 
  features:
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.path
    - navigation.footer



markdown_extensions:

  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Mermaid support
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # Footnotes
  - footnotes

  # Grids
  - attr_list
  - md_in_html

# Copyright
copyright: Copyright &copy; 2025 - 2026 Timothy Tao

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Bailitaotao
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@bailitaotao
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/325680073
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/bailitaotao/

  # Display "Made with Material for MkDocs"
  generator: false

extra_css:
  - stylesheets/extra.css
